### ISSUE TITLE
SCOT payout precision problem

### ISSUE THREAD

**Issue by economicstudio** [eonwarped/nitrous#2]
![](https://cdn.steemitimages.com/DQmUYA6uMbYsoiBJu7wWGFdoXVb1XTGsebpnoPWpX7n8hnZ)
> https://www.steemcoinpan.com/kr/@blockchainstudio/3o7w6f

The same problem exists in weedcash

**Comment by eonwarped** [comment]
Resolved with https://github.com/eonwarped/nitrous/commit/40bed4f7776ce8a58936c8ee78397b6bad686e1b

Now deployed.
